### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by vingov** [Intrinsec/comission#1]
We are running this command, in our CI pipeline to check for any pending security update for our Drupal code base, I was wondering does this project does the same set of tests or it performs additional checks?

```
drush ups --check-disabled --security-only --format=json
```

**Comment by upils** [comment]
Comission is focused on security. I'm not very familiar with drush, but comission can do the following tests : 
- get the drupal version used;
- get the last drupal version and compare;
- for each plugin, get the version used;
- for each plugin, get the last version published and compare;
- check if the drupal core have been altered by comparing with default drupal archive;
- for each plugin, check if the plugin have been altered by comparing with default archive;

Today, the tool is not able to check for CVE for drupal.

Is there any missing features you would like to be added ?
